notifications:
  email: false

language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
    - py.test
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
