notifications:
  email: false

language: python
addons:
  apt:
    packages:
    - python-xlib
    - python-pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
    - py.test --cov=WarDrivePiCar
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
