notifications:
  email: false

language: python
addons:
  apt:
    packages:
    - python-xlib
    - python-pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
    - py.test --cov=WarDrivePiCar
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
