notifications:
  email: false

language: python
addons:
  apt:
    packages:
    - python-xlib
    - python-pip
    - postgresql-9.4
    - psycopg2
    - vnc4server # to mock an X Server
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - echo -e "p4ssw0rd\np4ssw0rd\n" | vncserver -geometry 1024x768 :99
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
script:
    - py.test --timeout=60 --cov=WarDrivePiCar
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
