notifications:
  email: false

language: python
addons:
  apt:
    packages:
    - python-xlib
    - python-pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
script:
    - py.test --cov=WarDrivePiCar
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
