notifications:
  email: false

language: python
addons:
  apt:
    packages:
    - python-xlib
    - python-pip
    - postgresql-9.4
    - python-psycopg2
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
    - py.test --cov=WarDrivePiCar
after_success:
    - coveralls
  
branches:
  only:
      - master
      - dev
